FROM balenalib/rpi-raspbian:buster

MAINTAINER Gregory TARDIVEL

ENV DEV_MODE 0

RUN apt-get update && apt-get install openjdk-11-jre -y && apt-get clean

WORKDIR /app
COPY jserver-core/build/install/jserver-core /app

VOLUME /apps

ENTRYPOINT ["bin/jserver-core"]