# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: "15"
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Build with Gradle
      run: gradle test
    - name: Prepare cypress jar
      working-directory: jserver-cypress
      run: gradle jar
    - name: Start server
      run: gradle dockerRun
    - name: Prepare cypress tests
      run: npm install
    - name: Cypress tests
      run: gradle cypressRun
    - name: Stop server
      run: gradle dockerStop
