# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish to my repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout my repository
        uses: actions/checkout@v2
        with:
          repository: gr3gdev/maven-repository
          path: build/maven-repository
      - name: Publish package
        run: gradle publish
      - name: Push to my repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_TOKEN }}
        with:
          source-directory: 'build/maven-repository'
          destination-github-username: 'gr3gdev'
          destination-repository-name: 'maven-repository'
          commit-message: "Publish version"
          user-email: ${{ secrets.REPO_EMAIL }}
