# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish to my repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout my repository
        uses: actions/checkout@v2
        with:
          repository: gr3gdev/maven-repository
          path: build/maven-repository
      - name: Publish package
        run: gradle publish
      - name: Push on my repository
        run: |
          cd build/maven-repository
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add *
          git commit -m "publish version"
          git push
