# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish to my repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish
        run: gradle publish -Pgpr.user=gr3gdev -Pgpr.key=${{ secrets.REPO_TOKEN }}
