# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish to my repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout maven-repository
        uses: actions/checkout@v2
        with:
          repository: gr3gdev/maven-repository
          path: build/maven-repository
      - name: Publish
        run: gradle publish
      - name: Commit maven files
        run: |
          cd build/maven-repository
          git config user.name "${{ secrets.REPO_USER_FULLNAME }}"
          git config user.email "${{ secrets.REPO_EMAIL }}"
          git status
          git add *
          git commit -m "Publish version"
          git push https://gr3gdev:${{ secret.REPO_TOKEN }}@github.com/gr3gdev/maven-repository.git
